### ISSUE TITLE
Getting the code to run using python 3

### ISSUE THREAD

**Issue by putilatex** [knaggsy2000/stormforce#3]
Hi Danny,
I am thinking about getting an LD-250 to install at my house in Dresden (East Germany)
I am an Arch user so have been trying to get your code to run using Python 3.
I am almost there with the code but have one or two questions regarding the code. 
if you're not too busy it would be great to have a chat and if I can get it to run I would gladly 
share the code with you.
Cheers Sean

**Comment by knaggsy2000** [comment]
Sean, sorry for the delay in replying.  StormForce-XR is considered end-of-life whereas StormForce-MQ is considered to be the latest generation of the StormForce range despite having some more dependencies.  But what would you like to chat about?
